# Local Services

FROM node:18-alpine
WORKDIR /usr/app
COPY /Local_service/Local_app/package.json ./
COPY /Local_service/Local_app/package-lock.json ./
RUN npm ci --omit=dev

COPY /Local_service/Local_app/src ./src
CMD [ "node", "src/index.js" ]
# ----------