name: Local app - Functionnal tests

on:
  push:
    paths:
      - 'Local_service/Local_app/**'
  pull_request:
#    branches:
#      - 'feat/service-a-*'
    paths:
      - 'Local_service/Local_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        working-directory: Local_service/Local_app/tests/functionnal/dependencies/
        run: docker-compose build
      - name: Set redis container up
        working-directory: Local_service/Local_app/tests/functionnal/dependencies/
        run: docker-compose up -d db_local
      - name: Set tester container up
        working-directory: Local_service/Local_app/tests/functionnal/dependencies/
        run: docker-compose up tester