version: '3.9'

services:

  # Local sevices
  local_app:
    container_name: local_app
    image: local_app

  pulsor1:
    container_name: pulsor1
    image: pulsor
    environment:
      PULSOR_ID: "0001"

  pulsor2:
    container_name: pulsor2
    image: pulsor
    environment:
      PULSOR_ID: "0002"

  pulsor3:
    container_name: pulsor3
    image: pulsor
    environment:
      PULSOR_ID: "0003"
  
  broker:
    container_name: broker
    image: eclipse-mosquitto
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  # ----------

  # Cloud services
  cloud_app:
    container_name: cloud_app
    image: cloud_app-run

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=db_cloud
      - MYSQL_ROOT_PASSWORD=admin

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus
    volumes:
      - ./../dbstats:/etc/prometheus
      - dbstats_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
      
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GRAFANA_MYSQL_PASSWORD=password
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_ALERTING_EXECUTE_ALERTS=false
    volumes:
      - ./../Grafana/datasources/:/usr/share/grafana/conf/provisioning/datasources/
      - statsapp_data:/var/lib/grafana
    ports:
      - 3000:3000
      
  mysqld-exporter:
    container_name: mysqld-exporter
    image: quay.io/prometheus/mysqld-exporter
    command:
     - --collect.info_schema.tablestats
    environment:
      - DATA_SOURCE_NAME=root:password@(dbcloud:3306)/
    ports:
      - 9104:9104
  # ----------

# Volumes

volumes:
  dbcloud-data:
  dblocal-data:
  syncapi-data:
  broker-data:
  localapp-data:
  pulsor1-data:
  pulsor2-data:
  pulsor3-data:
  dbstats_data: {}
  statsapp_data: {}

# ----------