name: Cloud app tests

on:
  push:
    - branches:
        - main
    - paths:
        - 'Cloud_service/Api/**'



jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: Cloud_service/Api
      run: npm ci

    - name: Lint with ESLint
      working-directory: Cloud_service/Api
      run: npm run lint

      # Fail the workflow if ESLint errors are found
      if: ${{ failure() || success() }}
