name: Lint Typescript
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
        with:
          path: './Cloud_service/Api'
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          path: './Cloud_service/Api'
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'