name: Lint Typescript
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          pattern: '*.ts'