name: Lint Typescript
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: ESLint (JS/TS) Action 
        uses: iCrawl/action-eslint@v1
