name: Local app - integ tests

on:
  push:
    paths:
      - 'Local_service/Local_app/**'
  pull_request:
#    branches:
#      - 'feat/service-a-*'
    paths:
      - 'Local_service/Local_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        working-directory: Local_service/Local_app/tests/integ/dependencies/
        run: docker-compose build
      - name: Set redis container up
        working-directory: Local_service/Local_app/tests/integ/dependencies/
        run: docker-compose up -d
      - name: Run integ tests
        run: docker exec -d tester npm run test:integ